### ISSUE TITLE
disallow-adding-capabilities interferes with require-drop-all

### ISSUE THREAD

**Issue by KingCrunch** [kyverno/policies#119]
The policy [`pod-security/baseline/disallow-adding-capabilities`](
https://github.com/kyverno/policies/blob/main/pod-security/baseline/disallow-adding-capabilities/disallow-adding-capabilities.yaml) contradicts [`best-practices/require_drop_all`](https://github.com/kyverno/policies/blob/main/best-practices/require_drop_all/require_drop_all.yaml).

When I implement `require_drop_all`, which seems reasonable too, of course I _must_ add the capabilities, that are still required, for example `NET_BIND_SERVICE`.

I've installed Kyverno via Helm Chart and actually I'd like to keep at least the `baseline` policies. However, the policy in this form is too strict. The rule should only trigger, if add does include capabilities, which are not part of the default set.

See also https://kubernetes.io/docs/concepts/security/pod-security-standards/

> Adding additional capabilities *beyond those listed below* must be disallowed.
> Allowed Values
> 
>    Undefined/nil
>  AUDIT_WRITE
>    CHOWN
>    DAC_OVERRIDE
>    FOWNER
>    FSETID
>    KILL
>    MKNOD
>    NET_BIND_SERVICE
>    SETFCAP
>    SETGID
>    SETPCAP
>    SETUID
>    SYS_CHROOT

Additionally it seems the rule missed `ephemeralContainers`

**Comment by chipzoller** [comment]
@KingCrunch sorry for the late response. The two policies you point out are supposed to be mutually exclusive. The policy `disallow-add-capabilities` is defined in the Kubernetes [Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/). The policy `drop-all-capabilities` is not part of this set of standards. The idea is that a user may select either policy depending on their needs. If you wish to abide by a set of standards, you'd probably opt for the first one. If you'd rather have policies à la carte then you may opt for the second.

Also, the PSS were recently updated for Kubernetes 1.22 and they haven't yet been updated on the Kyverno side to pick up those changes (including ephemeralContainers which was only a recent feature).

I'll go ahead and close this issue because we will be updating those policies, but feel free to respond if you feel there's an additional action item here.
