### ISSUE TITLE
Policy to block calls on Node resources

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/policies#121]
See:

https://www.youtube.com/watch?v=6rMGRvcjvKc

> The attack could have been prevented, if the node authorizer blocked all calls to Nodes resource on the K8s API. I don't see any reason to allow node delete/create, when updates to Node taints are being blocked. 
It seems the security rules are setup conveniently for the demo scenario to work.

**Comment by CIPHERTron** [comment]
Heyy @JimBugwadia @realshuting, can I take up this issue? I would love to work on it.

**Comment by JimBugwadia** [comment]
Thanks @CIPHERTron!

**Comment by CIPHERTron** [comment]
> @CIPHERTron are you still working this issue?

Heyy @chipzoller my bad. Totally forgot about this issue. Currently, I'm working on the test command for generate policies. So, I'm gonna have to unassign myself. Thanks for notifying me.

**Comment by chipzoller** [comment]
I had a look at this presentation (in which this attack was demonstrated against Kubernetes 1.11 almost 2 years ago), and what was quoted was from a comment on the video. There have been some significant updates since this demo not only with NodeAuthorizer but even the default ClusterRole for kubelet (delete requests on node resources are disallowed, which was the first step in how the compromise was able to occur). There's nothing jumping out at me as far as a policy for admission controllers are concerned other than to maybe just reinforce that, cluster wide, node resources cannot be deleted. We may also be able to add a policy to disallow node taint removals which is similar to our existing policy to [restrict node label changes](https://kyverno.io/policies/other/restrict_node_label_changes/).
