### ISSUE TITLE
[Question] Should we create release branches to manage backward compatibility?

### ISSUE THREAD

**Issue by realshuting** [kyverno/policies#174]
Currently there's only one main branch and all changes / fixes will be merged into main, while this could bring an issue whenever we push out a patch release. Since some of the new features may not be backported to the patch version, should we create release branches and manage versioning stuff correspondingly?

**Comment by chipzoller** [comment]
How would this impact policies specifically especially since we use an annotation to state the  minimum version (minversion) as well as more recently the compatible versions of Kubernetes (kubernetes-version) and Kyverno (kyverno-version)? What problem does this solve?

If we cut a release, even if it's a patch, and these policies stop working, one or multiple things should happen in my mind.

1. It shouldn't have broken because there's supposed to be CLI validation using this library. Where there are coverage gaps we need to plug them.

2a. Kyverno should be fixed because this may be a bug or

2b. The policy needs to be brought up to date with the current functionality and the minversion annotation bumped in response.

**Comment by realshuting** [comment]
Since the patch releases only have the critical fixes for a minor version, all the new features won't be cherry-picked into the patch release branch. While the policy may already up-to-date reflecting latest changes. This results in CI failures as I'm currently generating 1.5.2 and have to cherry-pick last three feature commits into the 1.5 release branch in order to fix the failure. https://github.com/kyverno/kyverno/commits/release-1.5

If we create release branches as kyverno/kyverno does, I can point the CLI test of the kyverno/kyverno release branch to kyverno/policies release branch, so there won't be any issue.

**Comment by chipzoller** [comment]
Is this only a problem for policies written for 1.5.0?

**Comment by realshuting** [comment]
No the problem is for policies written for 1.6.0, and 1.5.2 don't have these supports.

**Comment by chipzoller** [comment]
Where in kyverno/policies do we have policies requiring 1.6.0?

**Comment by realshuting** [comment]
These policies require CLI 1.6.0:
https://github.com/kyverno/policies/blob/main/other/prepend_image_registry/prepend_image_registry.yaml
https://github.com/kyverno/policies/blob/main/other/pod_lifetime_annotation/enforce_pod_duration.yaml

And corresponding PRs:
https://github.com/kyverno/kyverno/pull/2673
https://github.com/kyverno/kyverno/pull/2569
https://github.com/kyverno/kyverno/pull/2560

**Comment by chipzoller** [comment]
Ok, so these tests are failing even in 1.5.1 so they should never have made their way there. Let's rename the test files temporarily so they don't get picked up by the CLI allowing everything to pass. We'll leave all the files there. Once these are working in the next release, we can rename them back to `test.yaml` so they get picked up again. How's that sound?

**Comment by realshuting** [comment]
I see a few issues by renaming `test.yaml`:
- we still want to run these tests from kyverno/kyverno main branch, how can we do that if we rename `test.yaml`?
- how do we inform other contributors to follow this?
- there must be someone do the job after a release, I prefer not to

By creating different branches we can point kyverno/kyverno branches to target a single branch, even for the tests that aren't working we can merge to a `staging` branch and merge to main once supported.

**Comment by chipzoller** [comment]
This is a one-time thing. The root of the problem here is that we allowed test cases to be written which we knew didn't work. That was a mistake from day one. If we follow good practices from here forward and this doesn't happen, do we still have a problem? If we're proposing creating branches just to solve this one problem, to me that's more overhead to solve a problem that shouldn't have existed to begin with.

**Comment by chipzoller** [comment]
Discussed over Slack. While this one issue might have been an isolated occurrence, larger concerns (which we have recently experienced) center around changing of the `PolicyReport` CRD which the `test` command uses which requires the test manifest structure changes. This can be a breaking change for earlier Kyverno versions which may still need support. Branching is a way to freeze these in place preventing any such breaking changes. By applying versioning to the schemas of these test manifests as raised [here](https://github.com/kyverno/kyverno/issues/2323), it should also help.
