### ISSUE TITLE
[Sample] [Karpenter] distribute pods among spot and on-demand based on weights 

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/policies#350]
### Problem Statement

>I don't think this is possible w/ Kyverno today, but we'd love to have a policy that would distribute pods among spot and on-demand based on weights. i.e. I want 20% of my pods w/ capacity-type on-demand and 80% spot.  Is this something you could write a policy for (or in the future)?

### Solution Description

One option to investigate is using a Pod Topology Spread Constraint:

https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/

https://karpenter.sh/v0.5.6/tasks/scheduling/#topology-spread

### Slack discussion

https://kubernetes.slack.com/archives/C02SFFZSA2K/p1657300277912829?thread_ts=1657299639.195769&cid=C02SFFZSA2K

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
Adding topology spread constraints shouldn't be a problem, but need more specifics as to what is required.

**Comment by chipzoller** [comment]
There is already a sample [here](https://main.kyverno.io/policies/other/spread_pods_across_topology/spread_pods_across_topology/) which adds topologySpreadConstraints to Deployments, and I think that's probably all we can do as far as this issue is concerned. I'm closing this for now but re-open if there's a more specific action we can take here.
