### ISSUE TITLE
investigate options for sample policies 

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/policies#4]

**Comment by chipzoller** [comment]
Would we be receptive to the idea of building policies out as a separate static site with a separate Hugo theme? I think that's going to give us the most freedom in pursuing the best UX with regard to tags and finding files.

**Comment by chipzoller** [comment]
Further to this month's meeting, some of the requirements we fleshed out were:

- Desire by users to apply, in GitOps fashion, curated standards like Pod Security Standards. This need entails organization of constituent policies into their own folder structure so Kustomize can process them accordingly.
- Need to ensure consistency and a system for automating unit tests (pass/fail) of each policy that gets created. Could be tested with the Kyverno CLI, for example. A possible implementation mentioned was ensuing test files reflect the name of the policy somehow.
- Acknowledging that users use example policies as teaching aids in order to learn Kyverno. There is desire to find policies of interest on an as-needed basis, which may be to learn the tooling but also to selectively copy and use in their environment.
- Other groupings (aside from the first bullet point) are subjective and arbitrary (i.e., "best practice" isn't necessarily everyone's best practice for everything) and may make it difficult to locate interesting policies.
