### ISSUE TITLE
drop-all-capabilities: "all" should be case insensitive

### ISSUE THREAD

**Issue by jemag** [kyverno/policies#413]
I should first preface this by mentioning that I am aware that this issue exists https://github.com/kyverno/policies/issues/109.

That being said, currently the provided policy will reject any policy that includes
```yaml
          capabilities:
            drop:
            - all
```

There are a couple of problems with this:
- A lot of 3rd party software comes with this `all` out of the box, including large CNCF projects such as coredns : https://github.com/coredns/deployment/blob/master/kubernetes/coredns.yaml.sed#L141-L146
- Even in the main Kubernetes GitHub repository, there are multiple manifests that use the form `all` (including gce kube-controller-manager, kube-scheduler and the kube-dns addon)
- Lastly, Kyverno should be enforcing the security requirements and throwing errors when those requirements are not met. Given that the form `all` works and implements the expected security, there should be no need to validate its syntax (case sensitivity) further

**Comment by jemag** [comment]
Thank you for the reply. 

Just to be sure, I am guessing similar modifications will be applied to [drop-all-capabilities](https://kyverno.io/policies/best-practices/require_drop_all/require_drop_all/)?

**Comment by chipzoller** [comment]
Yes

**Comment by joebowbeer** [comment]
@jemag Do you have a reference for the statement that lowercasing all of these capabilities works and implements the expected security? All I see in the description is support for the statement that the lowercase form exists in some places in the source code, which I do not doubt.

> Given that the form all works and implements the expected security

**Comment by jemag** [comment]
In terms of the documentation, you are right that I could not find an official statement about lowercase vs uppercase.

In terms of working, it is relatively straight forward to test, for example, here I have 3 containers, one using capital form (top right), one lower case form (bottom left) and one not dropping the capabilities at all (bottom right):
![image](https://user-images.githubusercontent.com/7985687/199835256-0f90e9f8-f111-4953-9496-044ff446b020.png)
![image](https://user-images.githubusercontent.com/7985687/199835469-38f137b4-217d-4ca0-95d7-858a4a1cf0c5.png)

The fact that it works and that numerous open source project as well as within the Kubernetes repository itself the form `all` is used is enough for me, but I agree that this should probably be better documented.

**Comment by joebowbeer** [comment]
Thanks for the demo!

What if it is specified as mixed case? Kyverno's new policy will accept that, too, but will Linux? 😄 

AFAICT, the PSA implementation is requiring all caps, and the last time I checked, Aqua's policy was as well.

I've actually fixed several of the lowercase exceptions, e.g., in ArgoCD and Grafana. In those cases, I used kyverno as a source of truth. (And I would prefer that kyverno hold the line...)

I assume the spec underlying this is Linux, and it would be nice to know how this is actually specified. If Linux is not case sensitive with respect to capabilities, then it's harder to argue for a stricter interpretation just because the PSS says so.

However, kyverno can also serve as a CLI static checker for PSA policies, and it would be unfortunate if kyverno and PSA disagreed about this.
