### ISSUE TITLE
Need some advice on livenessProbe and readinessProbe policy.

### ISSUE THREAD

**Issue by devendrakumar9-deloitte** [kyverno/policies#454]
### Problem Statement

We have a situation where i want to exclude (Job Kind and some selected pods) from liveness and readiness probe cluster policy. can someone please share example conditions or rule how to use to exclude these resources.

### Solution Description

can someone please share example conditions or rule how to use to exclude these resources.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
Sorry for such a long response. Can you be more specific as to the exclusions?

**Comment by chipzoller** [comment]
If you check the sample policy [here](https://main.kyverno.io/policies/best-practices/require_probes/require_probes/) (which was recently updated to simplify and extend the probe check), you'll see that Jobs are excluded. However, because Kyverno still applies policy to the Pods emitted from them, if you want to fully exclude Jobs you may need to use a precondition to exempt them. This is a precondition that should do that:

```yaml
    preconditions:
    - key: "{{ request.object.metadata.ownerReferences[].kind || `[]` }}"
      operator: AnyNotIn
      value: ["Job"]
```

For other Pod exclusions, you can use the `exclude` block described [here](https://main.kyverno.io/docs/writing-policies/match-exclude/#match-statements).

Closing this issue but respond if you still need assistance, or come talk to us on Slack in the #kyverno channel on Kubernetes Slack.
