### ISSUE TITLE
Feature Request: Add Git Tags & GitHub Releases to this repo

### ISSUE THREAD

**Issue by vyas-n** [kyverno/policies#916]
Hi Kyverno Policy Development Team,

I'm a big fan of Kyverno & the policies and actively use it as a part of my infrastructure.
    
When I do, I'm currently referencing this repo directly & using kustomize to tweak the policy to my needs (for example, changing `validationFailureAction` to `Enforce` depending on the policy). However, sometimes the policy changes when I wasn't expecting it to.
    
I wondered if you're willing to tag & release this repo with versioning so that I can reference a static ref of the repo and update my ref to the newer release once I've verified compatibility on my end.
    
Thanks,
Vyas

**Comment by vyas-n** [comment]
I'm not sure if this should be tracked in another ticket, but this versioning info could also be included in the ArtifactHub listings for Kyverno Policies: https://artifacthub.io/packages/search?kind=15

**Comment by chipzoller** [comment]
I get what you're trying to do, but it's probably not the best of ideas to directly deploy policies in this library to your environments. The closest thing you could do right now is reference release branches because we do cut those for every minor version and we typically don't cherry pick changes from `main` into them.

We could also increment the Artifact Hub version as well but you'd obviously need to fetch them from there.

I'm going to close this as not planned for now but happy to discuss.
